# Generated by Django 5.1.4 on 2026-02-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("text", models.TextField(verbose_name="Текст отзыва")),
                (
                    "rate",
                    models.CharField(
                        choices=[("PS", "Позитивно"), ("NT", "Нейтрально"), ("NG", "Негативно")],
                        default="NT",
                        max_length=2,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Review",
                        to="items.item",
                        verbose_name="Блюдо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыва",
                "verbose_name_plural": "Отзывы",
                "ordering": ["pk"],
            },
        ),
    ]
