# Generated by Django 5.1.4 on 2026-02-08 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_alter_usermeal_is_given"),
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="item",
        ),
        migrations.AddField(
            model_name="review",
            name="meal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Review",
                to="meals.meal",
                verbose_name="Блюдо",
            ),
            preserve_default=False,
        ),
    ]
