# Generated by Django 5.1.4 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("PT", "Ученик"), ("TC", "Повар"), ("AD", "Админ")],
                default="PT",
                max_length=2,
                verbose_name="user status",
            ),
        ),
    ]
