# Generated by Django 5.1.4 on 2026-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Принята"),
        ),
    ]
