# Generated by Django 5.1.4 on 2026-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0003_purchase_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="amount",
            field=models.IntegerField(default=0, verbose_name="Количество"),
            preserve_default=False,
        ),
    ]
