# Generated by Django 5.1.4 on 2026-02-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_remove_ingredient_cost"),
        ("purchases", "0004_purchase_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="ingridients",
        ),
        migrations.AddField(
            model_name="purchase",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="ingredients.ingredient",
                verbose_name="Ингредиент",
            ),
            preserve_default=False,
        ),
    ]
