# Generated by Django 5.1.4 on 2026-02-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("date", models.DateField(verbose_name="Дата")),
                ("day_index", models.IntegerField(default=0, verbose_name="Индекс дня недели")),
            ],
            options={
                "verbose_name": "День",
                "verbose_name_plural": "Дни",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("start_date", models.DateField(verbose_name="Дата понедельника")),
            ],
            options={
                "verbose_name": "Неделя",
                "verbose_name_plural": "Недели",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("cost", models.IntegerField(verbose_name="Цена")),
                (
                    "category",
                    models.CharField(
                        choices=[("BF", "Завтрак"), ("DN", "Обед")], default="BF", max_length=2
                    ),
                ),
                (
                    "day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meals.day",
                        verbose_name="День проведения",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="meals", to="items.item", verbose_name="Блюда"
                    ),
                ),
            ],
            options={
                "verbose_name": "Прием пищи",
                "verbose_name_plural": "Приемы пищи",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="UserMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("is_given", models.BinaryField(default=0, verbose_name="Выдан")),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meals.meal",
                        verbose_name="Прием пищи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь-Прием Пищи",
                "verbose_name_plural": "Записи",
                "ordering": ["pk"],
            },
        ),
    ]
