# Generated by Django 5.1.4 on 2026-02-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Week",
        ),
    ]
