# Generated by Django 5.1.4 on 2026-02-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_delete_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(unique=True, verbose_name="Дата"),
        ),
    ]
