# Generated by Django 5.1.4 on 2026-02-08 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0004_alter_day_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="meal",
            unique_together={("day", "category")},
        ),
        migrations.AlterUniqueTogether(
            name="usermeal",
            unique_together={("user", "meal")},
        ),
    ]
