# Generated by Django 5.1.4 on 2026-02-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0005_alter_meal_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermeal",
            name="is_given",
            field=models.BooleanField(default=0, verbose_name="Выдан"),
        ),
    ]
