# Generated by Django 5.1.4 on 2026-02-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0006_alter_usermeal_is_given"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="day",
            name="day_index",
        ),
    ]
