# Generated by Django 5.1.4 on 2026-02-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0007_remove_day_day_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="is_prepared",
            field=models.BooleanField(default=False, verbose_name="Приготовлен ли"),
        ),
    ]
