# Generated by Django 5.1.4 on 2026-02-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealreport",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата создания репорта"),
        ),
    ]
