# Generated by Django 5.1.4 on 2026-02-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="cost",
        ),
    ]
