# Generated by Django 5.1.4 on 2026-02-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_remove_ingredient_cost"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"verbose_name": "Ингредиент", "verbose_name_plural": "Ингредиенты"},
        ),
    ]
